### ISSUE TITLE
Panic due to failure to open font

### ISSUE THREAD

**Issue by wezm** [theiskaa/mdp#4]
```
thread 'main' panicked at src/lib/pdf.rs:40:14:
Failed to load font family: Error { msg: "Failed to open font file assets/fonts/roboto/roboto-Regular.ttf", kind: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" }) }
```

It seems that in this code lowercase `roboto` is returned:

https://github.com/theiskaa/mdp/blob/21e79baea6e05b8c9deae6244f12cda48f467641/src/lib/styling.rs#L15

However, on a case-sensitive filesystem (as it typical on Linux) this generated path is not found as the font is actually named `Roboto-Regular.ttf`:

```
ls -1 assets/fonts/roboto
Roboto-Black.ttf
Roboto-BlackItalic.ttf
Roboto-Bold.ttf
Roboto-BoldItalic.ttf
Roboto-Italic.ttf
Roboto-Light.ttf
Roboto-LightItalic.ttf
Roboto-Medium.ttf
Roboto-MediumItalic.ttf
Roboto-Regular.ttf
Roboto-Thin.ttf
Roboto-ThinItalic.ttf
```

**Comment by theiskaa** [comment]
That's good to know. I'm on Mac, but never had kinda problem.

Tho, I’m working on a dynamic approach to handle fonts, aiming to fix the issue by making text uppercase. However, I want to avoid adding too much font files to the repository. Instead, my goal is to use an external config or styling object to manage and customize the style components of the generated PDFs. Have you checked out the latest updates in styling.rs? And what do you think? What would be the "preferred" or "comfortable" way to use that feature?

**Comment by wezm** [comment]
> I'm on Mac, but never had kinda problem.

Yeah macOS uses a case-preserving, case-insensitive file-system by default: https://en.wikipedia.org/wiki/Case_preservation#Case-preserving,_case-insensitive

> Have you checked out the latest updates in styling.rs? And what do you think? What would be the "preferred" or "comfortable" way to use that feature?

I think ideally you'd be able to specify the font family you want to use and `mdp` would locate the font family on the system using something like https://lib.rs/crates/font-loader

**Comment by theiskaa** [comment]
Gotcha, thanks. Probably gonna need a weekend to focus and resolve both topics. But, will try my best to find some time before weekend.

**Comment by wezm** [comment]
No problem, and no rush. 👍

**Comment by theiskaa** [comment]
I can't test the case directly, but the proposed fix involves splitting the path into separate values for the directory path and file name. Pushing directly to the main branch. Please let me know the result, and I'll keep the issue open.

```rust
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum MdPdfFont {
    Roboto,
}

impl MdPdfFont {
    pub fn dir(&self) -> &'static str {
        match self {
            MdPdfFont::Roboto => "roboto",
        }
    }

    pub fn file(&self) -> &'static str {
        match self {
            MdPdfFont::Roboto => "Roboto",
        }
    }

    pub fn find_match(family: Option<&str>) -> MdPdfFont {
        match family.unwrap_or("roboto") {
            _ => MdPdfFont::Roboto,
        }
    }

    pub fn load_font_family(family: Option<&str>) -> Result<FontFamily<FontData>, Error> {
        let found_match = MdPdfFont::find_match(family);
        let path = format!("assets/fonts/{}", found_match.dir());
        genpdf::fonts::from_files(path.as_str(), found_match.file(), None)
    }
}
```

**Comment by theiskaa** [comment]
Changes are in this commit https://github.com/theiskaa/mdp/commit/861de2a80f332f3215c7bd5f00f25d1ea9ba6ebb

**Comment by wezm** [comment]
> I can't test the case directly

You can create a disk image with a case sensitive file system. If you build and run the project from that it will serve as a test. https://support.apple.com/en-au/guide/disk-utility/dskutl11888/mac

However, I tested `main` and it works (doesn't panic) now.

**Comment by theiskaa** [comment]
Great, that sounds good! I'll close the issue now. Thanks again for your contribution!
