### ISSUE TITLE
Styling from a config file

### ISSUE THREAD

**Issue by theiskaa** [theiskaa/mdp#5]
After merging PR #3, i've added the ability to customize virtually every aspect of generated PDFs through external configuration. The `Pdf` class now accepts a `StyleMatch` object that controls styling properties like padding, colors, dimensions, and other visual elements. Here's a basic example:

```rust
let parser = Pdf::new(tokens);
parser.create_document(StyleMatch::default());
```

To complete this feature, we need to implement several key components:

1. We need to add support for parsing external configuration files into `StyleMatch` objects. This will allow users to define their styling preferences in a separate config file.

2. We should decide on the configuration file format. JSON is the preferred option, though YAML could be an alternative if there's strong community preference.

3. We need to establish a conventional location for the configuration file, similar to how `.nvimrc` or other tool configs work. This should follow standard system practices for config file locations.

4. Finally, we need to implement commands that let users easily edit, modify, and reset their styling configurations.

Please share your thoughts on the configuration format preference or any other aspects of this implementation.

**Comment by wezm** [comment]
Thoughts:

2. JSON is really unpleasant as a user edited format as it doesn't support comments. YAML feels overly complicated to me (and is full of foot-guns like [the norway problem](https://hitchdev.com/strictyaml/why/implicit-typing-removed/)). I'd suggest looking into alternative such as [TOML](https://toml.io/en/), [Ron](https://docs.rs/ron/latest/ron/), and [kdl](https://kdl.dev/).
3. [directories](https://lib.rs/crates/directories) will help here

**Comment by theiskaa** [comment]
Great, that sounds good! I'll close the issue now. Thanks again for your contribution!

**Comment by theiskaa** [comment]
Oops, closed it by mistake! I agree, TOML could be a solid alternative.

**Comment by theiskaa** [comment]
i’ve implemented the configuration functionality using `.toml`, so it's ready for a demo! I'd love to hear your feedback: https://github.com/theiskaa/mdp/pull/6
