### ISSUE TITLE
Enable Link-Time Optimization (LTO)

### ISSUE THREAD

**Issue by zamazan4ik** [theiskaa/mdp#7]
Hi!

I noticed that in the `Cargo.toml` file Link-Time Optimization (LTO) for the project is not enabled. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance a bit. If you want to read more about LTO, I can recommend starting from [this](https://doc.rust-lang.org/rustc/codegen-options/index.html#lto) Rustc documentation.

I suggest enabling LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. If you think that a regular Release build should not be affected by such a change as well, then I suggest adding an additional `dist` or `release-lto` profile where in addition to regular `release` optimizations LTO will also be added. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most performant version of the application. Using ThinLTO should also help to reduce the build-time overhead with LTO. If we enable it on the Cargo profile level, users, who install the application with `cargo install` or building the Release Docker image, will get the LTO-optimized version "automatically". E.g., check `cargo-outdated` Release [profile](https://github.com/kbknapp/cargo-outdated/blob/master/Cargo.toml#L48).

Basically, it can be enabled with the following lines:

```
[profile.release]
lto = true
```

I have made quick tests (Fedora 41, Rustc 1.82) by adding `lto = true` to the Release profile. The binary size reduction is from 2.9 Mib to 2.5 Mib. It is not a big win but anyway! Later, when more functionality (and more possible dependencies) will be added, the win will be bigger.

Thank you.

**Comment by theiskaa** [comment]
Hey, thanks for the suggestion! I'm planning to release the library on Crates.io very soon, but I need to make a few updates first. Code parsing isn’t working correctly yet, and examples are missing (based on feedback from Reddit). Once those are resolved, I'll definitely enable LTO—didn't know about it before, so thanks for the tip!

**Comment by theiskaa** [comment]
This is pretty cool! The right side shows the previous state, and the left side displays the result after setting LTO to thin. It's impressive—thanks again for the suggestion.

<img height=300px src="https://github.com/user-attachments/assets/b627ea6f-1de4-44ca-9c4b-cc9c26456546">

The issue was resolved in commit: [ac1c2aa](https://github.com/theiskaa/mdp/commit/ac1c2aa5a2407a95c5679e58bb15df08ad12e538).
